title: Zhengyu Wang
subtitle: An enthusiastic programmer
description: >- # this means to ignore newlines until "baseurl:"
  A homepage of me

url: "https://JonatanWang.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: About Me
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Contact Me
    url: /contact

# Edit these details

author_logo: profile.png
author: Zhengyu Wang
author_bio: Hello, My Name is Zhengyu Wang. I love to Code and Design. This is my personal homepage as a developer.
author_email: "enar.wang@gmail.com"
author_location: Sweden
author_website_url: "http://JonatanWang.github.io"

author_work_experiences:
  - company_name: Cygni
    company_logo: cygni.png
    company_url: https://www.cygni.com
    designation: Consultant / IT System Developer
    description: Worked on various onsite projects
    visibility: true
  - company_name: Scania
    company_logo: scania.png
    company_url: https://www.scania.com
    designation: C# & Python Developer
    description: Worked on C# & Python projects
    visibility: true

author_education_details:
  - college_logo: kth.png
    college_name: KTH
    college_url: https://www.kth.se
    college_degree: Computer Engineering
    description: Bachelor of Technology(Högskoleingenjör av Datateknik)
    visibility: true

author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://hack4r.com
    visibility: true

# social links
github_username: JonatanWang
facebook_username: wang.hampus
linkedin_username: zhengyu-wang-65a7937b
telegram_username: levaral

#for comments using disqus
disqus_shortname: zhengyuwang

# wakatime username (coding activity)
wakatime_username: zhengyu

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://JonatanWang.github.io

# formspree (contact form)
formspree_email: enar.wang@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: "article"
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Gallery
defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
